# Pytorch Basic

In [1]:
import torch
import numpy as np
import matplotlib.pyplot as plt

device = "cuda:0" if torch.cuda.is_available() else "cpu"
device

'cuda:0'

### torch.tensor 함수

`tensor(data, dtype=None, device=None, requires_grad=False) -> Tensor`

     data (array_like): list, tuple, numpy ndarray, scalar, and other types.
     dtype :  `None`인 경우 `data`에서 데이터 유형을 유추합니다.  
     device : `cpu`, `cuda`  
     require_grad(bool, optional): autograd가 작업을 기록해야 하는 경우

Float torch tensor 생성

In [2]:
# numpy 생성
a = np.ones((2, 3), dtype="float32")
# tensor 생성
b = torch.tensor(a)
# dtype
print(a.dtype, '\t', b.dtype)

float32 	 torch.float32


Integer tensor 생성

In [3]:
x = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.int32)
x

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)

### Tensor 생성

- 무작위로 초기화된 행렬 생성 (uniform distribution)

In [4]:
x = torch.rand(5, 3)
print(x)

tensor([[0.8349, 0.3536, 0.3389],
        [0.2501, 0.9525, 0.6920],
        [0.0235, 0.0480, 0.9323],
        [0.0218, 0.4204, 0.5434],
        [0.5998, 0.7928, 0.9328]])


## Tensor 의 shape & dimension (rank)

In [5]:
a = torch.Tensor([0, 1, 2, 3, 4])
a.size()

torch.Size([5])

In [6]:
# size() 와 shape 은 alias
a.shape

torch.Size([5])

In [7]:
a.ndimension()

1

## numpy 와 tensor 간의 호환성

- memory 를 공유하므로 하나를 수정하면 나머지에 모두 반영  

In [8]:
numpy_array = np.array([0.0, 1.0, 2.0, 3.0, 4.0, 5.0])       # numpy array
torch_tensor = torch.from_numpy(numpy_array)               # torch tensor
torch_tensor

tensor([0., 1., 2., 3., 4., 5.], dtype=torch.float64)

In [9]:
back_to_numpy = torch_tensor.numpy()           # numpy array
back_to_numpy

array([0., 1., 2., 3., 4., 5.])

In [10]:
numpy_array, torch_tensor, back_to_numpy

(array([0., 1., 2., 3., 4., 5.]),
 tensor([0., 1., 2., 3., 4., 5.], dtype=torch.float64),
 array([0., 1., 2., 3., 4., 5.]))

In [11]:
back_to_numpy[0] = 100

numpy_array, torch_tensor, back_to_numpy

(array([100.,   1.,   2.,   3.,   4.,   5.]),
 tensor([100.,   1.,   2.,   3.,   4.,   5.], dtype=torch.float64),
 array([100.,   1.,   2.,   3.,   4.,   5.]))

## Scalar value

- 만약 tensor에 하나의 값만 존재한다면, ``.item()`` method를 사용하여 숫자 값을 얻을 수 있습니다.  

In [12]:
x = torch.randn(1)
x.item()

-1.610203504562378

In [13]:
a = torch.tensor([5., 3., 4., 1.])

print(a[0])
print(a[0].item())

tensor(5.)
5.0


- tensor 가 array 형태인 경우 `numpy()` method 를 통해 ndarray 반환

In [14]:
x = torch.randn(2)
print(x)
print()
print(x.numpy())

tensor([0.4030, 0.1265])

[0.40297014 0.1264578 ]


## Basic Operations - numpy 와 동일

In [15]:
# element-wise 덧셈, 뺄셈
u = torch.tensor([1.0, 0.0])
v = torch.tensor([0.0, 1.0])
z = u + v
z

tensor([1., 1.])

In [16]:
z = u - v
z

tensor([ 1., -1.])

In [17]:
# element-wise 곱셈
u = torch.tensor([1, 2])
v = torch.tensor([3, 2])
z = u * v
z

tensor([3, 4])

In [18]:
# 스칼라 곱
y = torch.tensor([1, 2])
z = 2 * y
z

tensor([2, 4])

In [19]:
# dot product
u = torch.tensor([1, 2])
v = torch.tensor([3, 1])
result = torch.dot(u, v)
result

tensor(5)

## TORCH.AUTOGRAD를 이용한 자동 미분

- autograd 패키지는 Tensor의 모든 연산에 대해 자동 미분을 제공   

- 신경망을 훈련할 때 가장 자주 사용되는 알고리즘은 역전파이다. 이 알고리즘에서 매개 변수 (모델 가중치)는 주어진 매개 변수에 대한 손실 함수의 기울기에 따라 조정된다.  

- 이러한 그래디언트를 계산하기 위해 PyTorch에는 torch.autograd라는 내장 미분 엔진이 있다.

- ``.requires_grad`` 속성을 True 로 설정하면, 그 tensor에서 이뤄진 모든 연산들을 추적(track)하기 시작  

- 계산이 완료된 후 ``.backward()`` 를 호출하여 모든 변화도(gradient)를 자동으로 계산  

- 이 Tensor의 변화도는 ``.grad`` 속성에 누적  

- Tensor가 기록을 추적하는 것을 중단하게 하려면, ``.detach()`` 를 호출하여 연산 기록으로부터 분리(detach)하여 이후 연산들이 추적되는 것을 방지한다.

- 도함수를 계산하기 위해서는 Tensor 의 ``.backward()`` 를 호출

In [20]:
x = torch.tensor(2.0, requires_grad=True)
x

tensor(2., requires_grad=True)

In [21]:
y = x ** 2
y

tensor(4., grad_fn=<PowBackward0>)

y 를 x 에 대하여 미분  
$$y(x)=x^2$$

$$\frac{dy(x=2)}{dx}=2x=4 \rightarrow {y.backward()}$$  

In [22]:
y.backward()

x.grad

tensor(4.)